# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daydays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='tokens',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token_read',
            field=models.CharField(max_length=200, verbose_name='token'),
        ),
    ]
