# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20)),
                ('intro', models.CharField(max_length=50)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('count', models.IntegerField()),
                ('gunit', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='upload')),
                ('isDelete', models.BooleanField(default=False)),
                ('textcontext', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='TitleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='image')),
                ('isDlete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.AddField(
            model_name='articlesinfo',
            name='sorts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.TitleInfo'),
        ),
    ]
