# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
