# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180409_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesinfo',
            name='crt',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
