# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlesinfo_crt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesinfo',
            name='crt',
            field=models.IntegerField(),
        ),
    ]
